### ISSUE TITLE
CMS for About page and Topics pages

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#10]
To allow Carter Center admins to edit/update content.

**Comment by jameslaneconkling** [comment]
* About Page
* Topics Pages (names will change, but an underlying id should stay the same.  there are 5 currently.  it is *not* a current requirement to expose adding new topics pages to CC admins):
  * EITI
  * Mining Code
  * Sicomines
  * State Enterprises
  * human rights

At a minimum, each page has the following:
* a title
* a banner image (if easy to do so, can include upload funtionality.  otherwise, link to a url, e.g. from flickr)
* Content, HTML formatted, supporting:
  * HTML elements: p, h1, a, strong, em, ul/li, img... (could be a good use case for markdown, or something similar
* a document category, or optionally multiple

**Comment by jameslaneconkling** [comment]
@markmcdonald51 Can we expand the current pages table to include about?  

url route must be http://baseurl/about

@charleshuang80 can you make sure that the nav bar in the header links to this page, when it's created?  The existing static about page can be deleted once the new one exists.

**Comment by charleshuang80** [comment]
@markmcdonald51 not sure which is easier, you could also make a controller and form for the existing about page (in static_pages_controller) in the admin section.

**Comment by jameslaneconkling** [comment]
@charleshuang80 @markmcdonald51 Forgot to bring this up again today.

Are we able to expand what we did with Topics Pages for the About page?
