### ISSUE TITLE
Loading Geodata is broken

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#101]
Returns 500 error:

```
http://188.166.93.154/drc_companies/48/get_deposits_geodata Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by charleshuang80** [comment]
@jameslaneconkling it needs to be aligned with the new way that deposits and reserves and minerals are set up. I'm sorting it out to fix it. Might be helpful if we can talk through how it's set up a bit.
