### ISSUE TITLE
issue with shareholder relations data input

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#105]
inputting a new shareholder relationship has a slick drop down that lets the user search for companies, and another slick field that allows the user to add multiple intermediary_companies.

However, when the user clicks *Créer un autre Relations avec les actionnaires* (create new shareholder relationship), these input fields don't work.

This is the case on both shareholder admin page and drc_company admin page

**Comment by markmcdonald51** [comment]
Hi James,

Going to need to see you do this. Seems to work like a charm  4 me!
