### ISSUE TITLE
Shareholder doesn't show for shareholder_relationship on drc_company admin page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#114]
Hey, the same issue is back for setting shareholders for shareholder_relationships on the drc_company admin page.  See here: http://188.166.93.154/admin/drc_companies/18-boss-mining/edit and here: http://188.166.93.154/admin/drc_companies

This was fixed when we checked it earlier today, but somehow it stopped working again?

**Comment by markmcdonald51** [comment]
pulled from drc companies for now at least and this relationship will only be editable from shareholders.
