### ISSUE TITLE
db search and advanced search

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#18]

**Comment by charleshuang80** [comment]
all working now except for shareholder companies

**Comment by charleshuang80** [comment]
Can reopen once we have shareholders

**Comment by jameslaneconkling** [comment]
The database has shareholders and shareholder_relationships now

**Comment by charleshuang80** [comment]
@jameslaneconkling closing for now as drc company and shareholders aren't in advanced search. Commented out drc company in search filtering and haven't hooked up shareholders.
