### ISSUE TITLE
Create Topics Pages

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#24]
Titles:

1. Minerals for Infrastructure
1. EITI
1. Mining Code
1. State Owned Enterprises
1. Human Rights & Mining

Each page will consist of a block of markdown-formatted content (text and optionally images), and a list of documents on a specific theme category.  Haven't figured out what those categories are yet, but will post here when I know.

The editing of these pages should be handled by a CMS (see #10 ), but should be possible to build the pages with static content before the CMS is built.

**Comment by charleshuang80** [comment]
@markmcdonald51 because of the CMS component (admin editing), should these sit in the admin section and be reassigned to you? Or do you want me to build out the pages and pull something that they can edit on the admin site (that you build out)?

**Comment by charleshuang80** [comment]
@jameslaneconkling the topics categories don't seem to line up exactly to Categories in our database. The following is what I've been able to match up as well as possible. Let me know what the missing one is and if I should use a different category for anything.

Sicomines
EITI Compliance      ["Transparence des Industries Extractives", 48]
Mining Code     ["Revision du Code Minier", 46]
Government Asset Sales (originally this said State owned Enterprises)      ["Gestion des entreprises étatiques", 45]
Human Rights    ["Mines, communautés locales et droits humains", 36]

**Comment by jameslaneconkling** [comment]
@charleshuang80 sorry for the late reply.

B/c there's not SICOMINES category, what about a search of the document table for document that contains the word 'sicomines' (not case sensitive, if possible).

**Comment by jameslaneconkling** [comment]
@charleshuang80 what's the status on this?  Currently, list of documents don't render.

**Comment by charleshuang80** [comment]
@jameslaneconkling are you talking about Sicomines or the other topics?
I am still working on the Sicomines, to associate a company with the page.
As for the other topics, last I checked (yesterday or day before), none of those topics had any documents associated with them.

**Comment by charleshuang80** [comment]
@jameslaneconkling if you have the latest db ( @markmcdonald51 just sent me one), in rails c you can do:

**Comment by jameslaneconkling** [comment]
ah shit.  Just looked up human rights and you're right, there are no results (see: http://188.166.93.154/search?search%5B%3Aquery%5D=&search%5B%3Atheme%5D=36&search%5B%3Atype_document%5D=&search%5B%3Atype_source%5D=&search%5B%3Aprovince%5D=)

But, the existing wp site does have a few responses: http://www.congomines.org/fr/category/themes/environ-social/droits-humains/

Which means the scrape must have missed them, or else they were dropped at some other point.  This is going to be a pain in the ass to fix up, but it'll be a pretty glaring issue if the topics pages don't show any of their intended documents.  Short of scraping the existing word press site (which doesn't sound very appealing), I can't think of any way to fix this except for manually editing everything.  @markmcdonald51 thoughts?

**Comment by jameslaneconkling** [comment]
also @charleshuang80 The Sicomines topic page should list a general query against the word 'sicomines', not just link to the company, if that's possible.

**Comment by charleshuang80** [comment]
@jameslaneconkling So you want this to run a search, instead of pulling associated reports?

**Comment by jameslaneconkling** [comment]
It should display a list of documents, like the other pages.  But that list
should be populated with any document that mentions 'sicomines', not just
the documents associated with the company sicomines ([here](
http://188.166.93.154/drc_companies/74)).

Make sense?

**Comment by charleshuang80** [comment]
@jameslaneconkling so I am running the search/query with 'Sicomines' and 'La Sino Congolaise Des Mines'. But the page is showing with 2 pages (24 or less) reports. The Sicomines company page has 4 pages (~37) reports. I'm not sure that these cover all the terms that refer to the company or what they're looking for. Please see if there are other search terms (i.e. some of the report summaries seem to have just 'Sino-Congolaise', is that enough to be a result?).

**Comment by charleshuang80** [comment]
@jameslaneconkling also you/they should know the search is only going through what we have in the databases, not what is in the attachments.

**Comment by jameslaneconkling** [comment]
yes, understood that attachments are not searched.

for the search, OK, should have realized that there were multiple search
phrases besides 'sicomines' that relate to the sicomines project (sicomines
is an abbreviation, and used to generally refer to Chinese investment in
Congolese mining).  So, do one of two things:
* just display all documents associated with the company 'sicomines' (since
that's the larger of the two sets)
* display all documents associated with company 'sicomines' or search query
'sicomines'.  i.e. the union of those two searches.

**Comment by charleshuang80** [comment]
@jameslaneconkling for now, I will make the sicomines topic page pull the ones associated with the company.
Need to do some testing but seeing if I can make the union work or not.

**Comment by charleshuang80** [comment]
@jameslaneconkling as for the topics, I think there may be 2 options (unless we can do a different scrape to tag the documents):
1, can't CC (or whoever is working with them) tag some of the appropriate reports so they'll pull properly?
2, are there other search terms we can try and use for each topic for the time being until reports get properly tagged/associated?

**Comment by jameslaneconkling** [comment]
@charleshuang80 OK, think it's fine if the Sicomines topic page just pulls documents associated with the sicomines company.  Only work on union-ing that w/ a general search query if it's easy.

As for getting the other Topics pages displaying the correct documents, ultimately, this is dependent on mark fixing the categories.  It appears that most documents dropped their category associations during the scrape (wish we had spotted this earlier, but oh well).  We could hack together a quick fix for the presentation on June 4, but ultimately the problem rests /w the categories.

**Comment by charleshuang80** [comment]
@markmcdonald51 Can you please change the setup for the pages setup, so that the page with topic Sicomines has category_id: nil, drc_company_id: 74
This is needed for it to render properly. The most recent database doesn't have this set up properly.
