### ISSUE TITLE
Download database extract as .csv option

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#30]
Allow any user to download extracts of the database.

Not all tables need to be downloaded, of course.  I'm thinking:

* all companies
* all mine deposits
* all processing infrastructure
* all social projects
* all shareholder relationships (this is a bit harder, as it should have a join onto both shareholders and drc_companies)

**Comment by markmcdonald51** [comment]
done

**Comment by jameslaneconkling** [comment]
where are these files output?  and how often are they updated?

**Comment by markmcdonald51** [comment]
they come right thru the browser.

**Comment by jameslaneconkling** [comment]
yes, but what's the url?
