### ISSUE TITLE
show recommended documents in views

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#34]
depends on #33 (there actually being a recommended field, and how that's set up: either yes/no, or ranked on some sort of numeric scale)

**Comment by charleshuang80** [comment]
Notes for me on specifics for this issue:
- tag some random recommended documents
- recommended documents section on index page goes away if there are no recommended documents
    - same on home page
- search results, if there are recommended documents there is a recommended documents section
  only show 4 recommended documents
  no duplicates
  can use same 4 recommended docs on subsequent paginated pages
  recommended documents does not take away from 3 rows of 4

**Comment by charleshuang80** [comment]
@jameslaneconkling this is done except for recommended documents in the search results, as we discussed.
Recommended Documents sections on index and home pages are set up to disappear if no recommended documents. Currently no documents marked as recommended.

**Comment by charleshuang80** [comment]
@jameslaneconkling do we need to keep this open for search results or can we close this?

**Comment by jameslaneconkling** [comment]
can close now
