### ISSUE TITLE
Company page URL should be company name, not id

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#4]
E.g. http://188.166.93.154/drc_companies/kamoto_copper_company , not http://188.166.93.154/drc_companies/6

**Comment by jameslaneconkling** [comment]
would need to validate company name as unique, which it should probably do anyway.

**Comment by jameslaneconkling** [comment]
also, cleaner urls if we can change congomines/drc_companies/<company_name> to congomines/companies/<company_name> .

**Comment by charleshuang80** [comment]
try and use https://github.com/norman/friendly_id

**Comment by charleshuang80** [comment]
set up to be, i.e.: /drc_companies/18_Boss_Mining

**Comment by jameslaneconkling** [comment]
@charleshuang80 just responded to the same thing w/ Topics pages.  Is it possible for this to be `/drc_companies/Boss_Mining` rather than `/drc_companies/18_Boss_Mining`?
