### ISSUE TITLE
Build model to hold mapbox tilesets

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#40]

**Comment by jameslaneconkling** [comment]
table does not have relationships with any other table

fields:
* id
* label

**Comment by charleshuang80** [comment]
@markmcdonald51 I created the migration and the model. Can you add it to the admin section so they can edit it?

**Comment by jameslaneconkling** [comment]
@charleshuang80 id needs to be text.  Looks like it's currently numeric.  This is a priority for the soft launch tomorrow.

**Comment by jameslaneconkling** [comment]
@markmcdonald51 if you have a moment, maybe you can fix this?

**Comment by charleshuang80** [comment]
done
