### ISSUE TITLE
Model Validations

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#41]
validate for presence of:

**documents**
* title
* source
* summary

**companies**
* name

**shareholder relationships**
* shareholder
* drc_company

**Comment by markmcdonald51** [comment]
done

**Comment by jameslaneconkling** [comment]
will reopen if/as these expand.

**Comment by jameslaneconkling** [comment]
Looks like shareholder_relationships is missing validation on `shareholder` and `drc_company`.

Possible to add these?

**Comment by markmcdonald51** [comment]
this works now.
