### ISSUE TITLE
Database search shouldn't be cached

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#46]
If I run a search on the admin pages, close the browser, and open it again, the search results still show.  (caused some momentary confusion).  

Probably better for there to be no filter on load (regardless of past user-applied filters)

**Comment by markmcdonald51** [comment]
this is a deep seeded function that is pretty slick if you understand the filter. Might be worth the explaination. It also displays '(Filtered)' when it is being used.

**Comment by jameslaneconkling** [comment]
Yeah, I'm not particularly worried about it.

Maybe it's possible to automatically trigger the 'reset filter' button on
load?

In any case, a pretty low priority.

**Comment by jameslaneconkling** [comment]
closing this, as likely not an issue.
