### ISSUE TITLE
Truncate document summary text on library page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#5]
so document elements align horizontally

**Comment by charleshuang80** [comment]
should I try and limit/truncate the title as well?

**Comment by charleshuang80** [comment]
@jameslaneconkling this is truncated just for the summary. Please review and let me know how long we should allow the summary to be. If you want to change yourself, it is in the _documents.html.slim partial (in app/views/shared), in the truncate function, you can alter the length that is passed.

As referenced above, the titles can be quite long, so we might want to consider truncating them, or inform me if we don't want to do that.

**Comment by jameslaneconkling** [comment]
OK.  I'm tracking a better way to handle this, with cleaner cutoff, ellipsis, which will handle both titles and summaries on #22 .

add comments there.
