### ISSUE TITLE
shareholder_relationships should have 'intermediary company' field

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#50]
That accepts multiple text values.  This could either be
* text field with comma separated values
* one_to_many relation with a 'intermediary company' table (probably the better way to go)

Input should be clear on the shareholder input form add company input form.

**Comment by markmcdonald51** [comment]
one_to_many relation done.

**Comment by jameslaneconkling** [comment]
Sorry for the flip-flopping on this one.

Carter Center said they thought creating a new table was unnecessary, and that a free text field would suffice (which they will populate with a comma-separated list of intermediary companies).  I told them the drawbacks to this approach (no validation, no search for intermediary companies, no guard against multiple spellings, etc.) and they were unconcerned.

So, change one_to_many relationship to a text field.
