### ISSUE TITLE
add tilelayers to map page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#51]
on dropdown click, add a new tilelayer to the map and remove all existing tilelayers (see dropdowns on template site [map page](http://crowdcover.github.io/congo-mines/map/), though if necessary, recreate the dropdown as you see fit.

tilelayers should be defined in maplayer table (see #40).

I can write the actual leaflet functions to add/remove each tilelayer, once the dropdown is created, w/ event handlers, etc.

**Comment by charleshuang80** [comment]
@jameslaneconkling the dropdown is created, but I don't know what layers to try and pull with (or test with)

**Comment by jameslaneconkling** [comment]
Once #40 is fixed, all tilelayers should populate the Maps Dropdown.

Testing shouldn't be an issue.  Just make dummy data for your local database.

Label should of course be the link test.  Best practice is to pass the map-id as an html data attribute.  E.g.

`
<a href="#" data-id="{mapid}">{label}</a>
`

**Comment by charleshuang80** [comment]
So we're just populating the dropdown from the table, and not talking about actually rendering anything, right?

**Comment by jameslaneconkling** [comment]
Yeah.  I'll get the layers to render w/ leaflet

**Comment by charleshuang80** [comment]
done
