### ISSUE TITLE
sort drc_company and shareholder alphabetically on company index page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#52]

**Comment by charleshuang80** [comment]
@jameslaneconkling so I need to add shareholder companies to the company index page (as we discussed previously), right?

**Comment by charleshuang80** [comment]
@jameslaneconkling should we make the select2 dropdowns alphabetical also?

**Comment by jameslaneconkling** [comment]
yeah, sounds like a good idea.

I'm mocking up some stuff on the page right now.  will push changes in a sec.

**Comment by jameslaneconkling** [comment]
ok, just pushed changes.

**Comment by jameslaneconkling** [comment]
to do:

- [ ] hook up shareholder search
- [ ]  populate shareholder column with shareholders (right now it's just displaying companies)
- [ ] sort both alphabetically
- [ ] swap out the X for a magnifying glass icon
