### ISSUE TITLE
year dropdowns on data input form

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#56]
* should be sorted descending (2015,2014,2013...)
* should only go back as far as 2000
* do these update automatically?  meaning, in 2016, will there automatically be another year added?  If not, perhaps we should change this to a number field.

this applies to all fields that represent a year

**Comment by markmcdonald51** [comment]
config.columns[:year].form_ui = :select
    config.columns[:year].options = {include_blank: 'Select Year', options: (1950..Time.now.year) }

done!

**Comment by jameslaneconkling** [comment]
Not a big deal, but is it possible to change this to `(Time.now.year..2000)`, so that is displays 2015 at top of drop down?
