### ISSUE TITLE
'import_customs_duty' field on tax_obligations table should be numeric

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#57]
currently, it's a a checkbox (boolean?).

**Comment by charleshuang80** [comment]
@jameslaneconkling I can take care of this I think most database related things Mark has been taking care of. Do you want this to be integer or float?

**Comment by jameslaneconkling** [comment]
Make it float.

The majority of tickets I just filed are assigned to mark, though some of
the more straightforward ones I assigned to you as well. In any case, there
should be plenty of work to tag team on. Feel free to reassign if necessary.

**Comment by markmcdonald51** [comment]
Done. I am just going to keep all of these fields as integer value unless the cent (floating point) is really necessary. Please advise.  I changed it to integer.

**Comment by jameslaneconkling** [comment]
Integer is probably better for (we're talking about hundreds of thousands
of dollars, I don't imagine they'll want to display cents).  Will report
back if they say otherwise.

**Comment by charleshuang80** [comment]
@markmcdonald51, you commented 'Done', but the schema that I have doesn't reflect that change or migration. Am I missing something or is this not totally done yet?

**Comment by charleshuang80** [comment]
Done
