### ISSUE TITLE
Admin labels representing $$$ need USD attached to them

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#58]
any field documented in the [companies](https://docs.google.com/spreadsheets/d/1BXxaJubvt98t2qil4y6w0DCkpji9tUCkceJ3ywGFNeA/edit#gid=1153549099) documentation with a **type** equal to *numeric ($)*  needs to have **(USD)** added to the end of the label on the admin page.

![screenshot 2015-05-15 15 13 06](https://cloud.githubusercontent.com/assets/4389360/7660060/ed98f484-fb14-11e4-84fe-576a364422c6.png)

**Comment by markmcdonald51** [comment]
Hey James, thinking we could just edit these in the translations so they will display correctly in all languages. Hit me up when you have a sec and either I or you can do this. It is pretty easy but needs to be complete to work correctly.

**Comment by jameslaneconkling** [comment]
OK, then let's hold off on this until we get to translations.  Tracking that at #70

**Comment by jameslaneconkling** [comment]
@charleshuang80 transferring this to you, as I think you are in charge of updating the form labels (as tracked in #70), yeah?
