### ISSUE TITLE
expand company table with field for 'permits'

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#62]
A company can have 0+ permits

They suggest a free text field for a comma-separated list.  Might make more sense to break out into a new table, so long as data input is easy.

**Comment by markmcdonald51** [comment]
James, I can do this either way. What is the data that they need to put in? Can you give me an example so I can create this. Thanks.

**Comment by jameslaneconkling** [comment]
Let's build it as a free text field for comma separated list input.  (they insisted they thought this was better).

**Comment by markmcdonald51** [comment]
done
