### ISSUE TITLE
employees table

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#64]
replace existing fields w/

* congolese male
* congolese female
* congolese total
* expat male
* expat female
* congolese total

**Comment by markmcdonald51** [comment]
Hey James, do you want me to turn this into a select field for gender for congolese male/female, textfield for total, select for expat male/female... the last field appears to be a duplicate. Please advise.

**Comment by jameslaneconkling** [comment]
ah, good thinking, but not quite.  congolese_male, congolese_female, and
congolese_total are all counts of the number of congolese employees (so
integer input for each).  Ditto with expat_male, expat_female, and
expat_total.

I told them that total is of course redundant, as it can be computed
automatically by adding male and female, but they wanted to keep it.  (I
can only give them my advice--I'm not going to argue if they don't take it)

**Comment by charleshuang80** [comment]
@markmcdonald51 did you do this? If not I can do it, just let me know. The schema that I have doesn't reflect the changes listed here.

**Comment by charleshuang80** [comment]
Done
