### ISSUE TITLE
figure out best way to load js assets

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#7]
Spent some time looking into this.  I'm sure there are lots of ways to modularize js in rails, but the simplest way--since each module *is* loading in the right order--would be to move [this](https://github.com/crowdcover/congo-mines-app/blob/master/app/assets/javascripts/application.js#L49-L51) from application.js to each view that has a map.  So, on these pages only, slim would render something like:

```
$(function(){
  app.initMap();
});
```

Thus, all pages would run `$(document).foundation();` and `app.initCommon();`, but only pages with a map would run `app.initMap()`.

One question, though, does app.initMap(); or app.initMap() run first?

**Comment by jameslaneconkling** [comment]
@charleshuang80 I think the pattern we figured out today should be good for this.

Feel free to close once you've changed leaflet to load via the manifest (or whatever the hell)

**Comment by charleshuang80** [comment]
@jameslaneconkling this is still not always loading the first time on linking to a drc_company page

**Comment by charleshuang80** [comment]
sorry, above comment was referring to the map. Also, this is not a consistent error/bug. It works most of the time.

**Comment by jameslaneconkling** [comment]
#8 refers to this bug specifically, as well as other parts of the site that exhibit similar (probably related) buggy behavior.

this thread can be closed when leaflet assets are loaded via the manifest

**Comment by charleshuang80** [comment]
@jameslaneconkling for the demo, I made the leaflet load on all pages in the _dochead.html.slim partial. But this is not ideal. When I tried downloading leaflet.js to vendor/assets, the map was not rendering/finding the marker images. Even after I put in the images to vendor/assets/images or app/assets/images, something was not working properly. Will need to revisit after the demo.

**Comment by jameslaneconkling** [comment]
@charleshuang80 how's this look now?  Once this is set up to a good enough standard for a handoff, feel free to close.  If there are any lingering issues, document them here.
