### ISSUE TITLE
Category selection for Documents 

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#74]
There should be four different input forms for each category type: Document Theme, Document Type, Source Type, and Province.  (currently there is one input field that selects from all available categories)

Documents shouldn't be able to be tagged by a category types (e.g. Theme, Province, Type de Document).  In the case of Themes, 2nd level themes (aka theme groups) (e.g. Aspects Financiers, Aspects Sociaux et Environmentaux, Contrats et Titres Miniers) shouldn't be able to be applied as a tag either.

This might require rethinking how we store categories, possibly moving away from the child-nesting approach we currently have to a more explicit, inflexible approach.  One possibility, create separate doc theme, doc type, source type, and province models, each with has_many association to a category model that only contains the lowest level categories.

**Comment by markmcdonald51** [comment]
putting this on hold to think out a fix...

**Comment by jameslaneconkling** [comment]
what we have in place should be good enough for now
