### ISSUE TITLE
Reorder admin input fields according to data documentation order

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#78]
Change order of fields on input forms to match the order of fields in [geo-data spreadsheet](https://docs.google.com/spreadsheets/d/1FhdHEGWVYgImtm10Hj5B35F2WvQs5GyZWaD52zrClgk/edit#gid=1720156906) and [company spreadsheet](https://docs.google.com/spreadsheets/d/1BXxaJubvt98t2qil4y6w0DCkpji9tUCkceJ3ywGFNeA/edit#gid=0)

**Comment by markmcdonald51** [comment]
done
