### ISSUE TITLE
Company maps don't load when navigated to from index page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#8]
Might be fixed by #7

**Comment by jameslaneconkling** [comment]
also, sticky nav bar throws and error (and doesn't work) when navigating from one page to another, but does when refreshing the page.

**Comment by jameslaneconkling** [comment]
would be curious to know if this happens on production, or just locally

**Comment by charleshuang80** [comment]
@jameslaneconkling I think this works now b/c of adding the js to application.html instead. However, #7 still presenting a problem when I tried to download leaflet.js into vendor/assets

**Comment by jameslaneconkling** [comment]
fantastic--looks like the js is running now.  (will take a look to see how you structured everything)

closing
