### ISSUE TITLE
topics pages urls should be the name of topic

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#85]
e.g. http://188.166.93.154/pages/10

should be 

http://188.166.93.154/human_rights

(or whatever the topic name happens to be)

**Comment by charleshuang80** [comment]
@jameslaneconkling it is setup for the url to be:
/pages/5-Human_Rights
Does that work?

**Comment by charleshuang80** [comment]
@jameslaneconkling how important/necessary is it to take out the preceding numbers for this issue and drc companies?

It is doable, but I will have to do a database change and maybe coordinate with @markmcdonald51 on populating a column for the urls. More importantly, it will change how the urls/references are treated in all the views (potentially in the admin part also).

**Comment by jameslaneconkling** [comment]
Not a priority, though it would be nice to have.

**Comment by charleshuang80** [comment]
ok, let's discuss when we talk next. As I mentioned, doable but might be best to wait until there is more time to test all links
