### ISSUE TITLE
Fix layout on drc_companies show page

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#87]
Now that company pages are populated with data from the db, we need to fix the layout.

@charleshuang80 I'll do my best to take the lead on this--will try to work on it over the weekend.  Feel free to take a look at it yourself, though, if you have time.

**Comment by charleshuang80** [comment]
I'm not sure what you mean by fix the layout, can you be more specific?

**Comment by jameslaneconkling** [comment]
sorry.  e.g. here: http://188.166.93.154/drc_companies/12

layout of Info in any of the dropdowns is broken.

attribute table overflows the page a lot and is not centered.

this is mostly foundation stuff (html/css).  I'll try to have a look this
weekend.
