### ISSUE TITLE
Shareholder admin form can't select company for shareholder relationship

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#89]
when editing shareholder_relationship from the shareholder data input form, the options are *percentage*, *year*, and *intermediary company*, but no option for *company*.

**Comment by markmcdonald51** [comment]
If you are editing this data from within a DrcCompany then it can only edit it's data, hence the fact that that option does not appear. If you look at http://188.166.93.154/admin/shareholders you will see that it does give one the option to add a DRC Company.
