### ISSUE TITLE
Search keeps breaking on production

### ISSUE THREAD

**Issue by jameslaneconkling** [crowdcover/congo-mines-app#95]
Can't recreate this consistently, so don't know how to pin point what's wrong.  But frequently search will either return a 500 error:
`
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
`

or will navigate to `http://188.166.93.154/a` and return a 404 error.

This might have to do with pushing work up to production.  But if so, we need to figure out what makes the search fragile and either find a way to make it more robust or minimize whatever actions it is that produces the errors.  We can't have search failing on production.

@charleshuang80 @markmcdonald51 Any thoughts?

**Comment by charleshuang80** [comment]
@jameslaneconkling I found the source of the /a 404 error. It is because of the change in _search.html.slim, line 16 (I wasn't able to get the reference link like you showed me) to:
a.button.postfix[href="a"] Search Library
from:
button [style="width: 100%"] Search Library
Instead of submitting the form, it tries to go to /a
I am changing it to:
button.postfix Search Library
The formatting isn't exactly the same, but maybe you can add whatever formatting was for a.button.postfix to button.postfix (or we can give it another class or id)

**Comment by jameslaneconkling** [comment]
OK.  Good to know.  You've pushed the changes?  If so, I'll pull them down and double check the style and fix up if necessary.

**Comment by charleshuang80** [comment]
yes, changes are pushed.

Don't know what was causing the 500 error though. Was that happening on the
production server?
If you're doing stuff on your local machine you should probably also run a
rake sunspot:solr:reindex (after a sunspot:solr:start to make sure it's
running)

On Wed, Jun 3, 2015 at 9:09 PM, James Conkling <notifications@github.com>
wrote:

> OK. Good to know. You've pushed the changes? If so, I'll pull them down
> and double check the style and fix up if necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdcover/congo-mines-app/issues/95#issuecomment-108668456>
> .
>



-- 

charleshuang.me
www.linkedin.com/in/charleshuang8

**Comment by jameslaneconkling** [comment]
Yeah, it was on production, which is why I'm worried.  Because it's not
consistent, it's really hard to diagnose properly.

**Comment by charleshuang80** [comment]
We can't test again until @markmcdonald51 pulls the changes, adds the filter to the solr/schema.xml (as referenced in https://github.com/crowdcover/congo-mines-app/issues/94), and runs a reindex. If there are still problems, we'll need mark to check the log files for us

**Comment by jameslaneconkling** [comment]
OK, fixed layout of search button.  Assuming this has solved the 404 error.

Keep this open for now until we can better diagnose the 500 errors.
