### ISSUE TITLE
browse submit button doesn't work

### ISSUE THREAD

**Issue by kriscarle** [crowdcover/congo-mines-app#99]
enter a search query, open the browse panel and select an option from the drop down, then click submit, and nothing happens. Don't see anything in the JS console

**Comment by markmcdonald51** [comment]
Ok. I just saw this who panel.  Need to know what exactly how this should work before I program it. 


![screenshot from 2015-06-09 14 27 12](https://cloud.githubusercontent.com/assets/39400/8066099/b7c85f90-0eb3-11e5-82b5-957546125bd8.png)

**Comment by markmcdonald51** [comment]
fixed
